sudo: true
language: python
python:
  - 2.7
rvm:
  - 2.2.4
before_install:
  - rvm get stable --auto-dotfiles
  - rvm install 2.2.4
  - gem install bundler -v 1.16.1
before_script:
  - pip install --user awscli
  - ./ci/travis/setup.sh
jobs:
  include:
    - stage: build
      script:
        - ./ci/travis/build.sh all
    - stage: test
      script:
        - cd python
        - python smoffice.py -a 5564b7d5-4def-498b-ad5b-d4f12a463275
        - cd ..
    - stage: deploy
      script:
        - ./ci/travis/deploy-artifacts.sh
