sudo: true
language: python
python:
  - 2.7
rvm:
  - 2.2.4
env:
  global:
    - DISPLAY=:0.0
before_install:
  - rvm get stable --auto-dotfiles
  - rvm install 2.2.4
  - gem install bundler -v 1.16.1
install:
  - pip install -r requirements.txt
  - cd data && bundle install && cd ..
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - ./ci/build.sh all
#after_success:
#  - ./ci/deploy-artifacts.sh
