sudo: true
dist: xenial
python:
  - 3.7
language: python
rvm:
  - 2.5.1
services:
  - xvfb
before_install:
  - gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
  - rvm get stable --auto-dotfiles
  - rvm install 2.5.1
  - gem install bundler -v 1.16.1
install:
  - pip install -r requirements.txt
before_script:
#  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
env:
  global:
    - DISPLAY=:99.0
  matrix:
    - TOX_ENV=python
    - TOX_ENV=flake8
    - TOX_ENV=docs
script:
  - tox -e $TOX_ENV
#  - ./ci/build.sh all
#after_success:
#  - ./ci/deploy-artifacts.sh
